### ISSUE TITLE
Feature Request: Check if nodejs is installed

### ISSUE THREAD

**Issue by shawnholt** [civicrm/civicrm-buildkit#160]
I know it is listed as a req but might be nice to check first.  For bonus check if sourceforge is actually up - that took me a while to figure out :)

**Comment by totten** [comment]
The current code in `civi-download-tools` should be treating it as a recommendation rather than a requirement, ie

https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L168
https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L256

Strictly speaking, one should be able to use buildkit with older versions of Civi (eg 4.4 LTS) without NodeJS, but it does seem to be creeping up from "recommended" to "required" (now that 4.6 is stable and now that civilint uses it). So I'm +1 for treating it as required but will give a pregnant pause in case any of the watchers have a contrary argument.

**Comment by totten** [comment]
See https://github.com/civicrm/civicrm-buildkit/pull/173
