### ISSUE TITLE
Calling node on Debian sid fails because it's installed as "nodejs".

### ISSUE THREAD

**Issue by openbrian** [civicrm/civicrm-buildkit#171]
When this happens a simple simlink from /usr/local/bin/node to /usr/bin/nodejs works.

**Comment by totten** [comment]
Yeah, it's annoying. You can't write scripts or docs which use the standard `node` command (because that breaks on Debian), and you can't write scripts or docs which use Debian's `nodejs` command (because that breaks everywhere else). 

I think the best prospect would be to patch [`civi-download-tools`](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L261) to explicitly check for the Debian situation and either:

 * Autocreate a symlink from `buildkit/bin/node` to `/usr/bin/nodejs`
 * Encourage the user to install `nodejs-legacy`. (Which is a bad name... but whatever.)

**Comment by totten** [comment]
@openbrian , I've merged https://github.com/civicrm/civicrm-buildkit/pull/173 . I didn't test a full/clean install, but it did work in quick/hacky testing.
