### ISSUE TITLE
Drush version bundled with buildkit doesn't support drupal 8

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-buildkit#175]
In theory we can switch to the version that does - although it is beta & may be less stable

**Comment by totten** [comment]
FWIW, drush 8.0.0-beta14 requires PHP 5.4.5... which is a bit of a problem for the test servers... the test servers need to run the build+test on PHP 5.3.x (since that's the officially supported version for all recent/current versions of Civi).

The only solution I can see is to have multiple copies of drush (e.g. `extern/drush-8` vs `extern/drush-7`).

**Comment by totten** [comment]
Previously resolved/discussed elsewhere. We now have `bin/drush8` available, which does work on Drupal 8.
