### ISSUE TITLE
Include need php5-curl in the requirements?

### ISSUE THREAD

**Issue by joannechester** [civicrm/civicrm-buildkit#179]
Just a suggestion - My first attempt at installing buildkit failed because I didn't have it

**Comment by totten** [comment]
I'm adding some PHP extension checks with https://github.com/civicrm/civicrm-buildkit/pull/180 . This should also mitigate the common problem of installing without `mysql` and `pdo` extensions.

`civi-download-tools` is kind of a nice place to check for extensions because it comes early in the process (fails fast) and can reference dependencies for both `civicrm-core` and random CLI tools. OTOH, this doesn't detect inconsistencies among SAPIs (php-cli vs php-cgi vs php-fpm vs mod_php5), and it doesn't work with other install methods, so it's not a full substitute for including checks directly in `civicrm-core`. But above all else, putting the test in buildkit/`civi-download-tools` is simple/expedient.
