### ISSUE TITLE
Modularizing buildkit (unit-testing)

### ISSUE THREAD

**Issue by AbdealiJK** [civicrm/civicrm-buildkit#238]
@totten and I had spoken yesterday about adding tests for buildkit.

So, I began trying to write unit-tests to check the bash functions (as they're the most common in the repo). While doing this I found it very difficult to test basic functions because it's tough to import them. It's not modularized from the script inside the `bin` folder.

Ideally we should have `lib` files for each of the `bin` files which contain all of the functions independently and then source the `lib` into the `bin` to use them as required.
Also, some small functions like `absdirname()` are being using in multiple locations (`releaser`, `phpcs-civi`, `gitify`, `civilint`, `civibuild`, and `civi-download-tools`). We should move them to a common `lib` file.

I notice that something like this is already there for `civibuild` - It has a `src/civibuild.lib.sh`.
Unless it's appropriately modularized, it becomes difficult to add unittests for functions.

Is this something that's wanted ?

If yes, what sort of directory structure should be followed ? I was thinking:
```
.
|-- bin
|   |-- civibuild
|   |-- cividist
|   `-- etc ...
|-- src
|   |-- common.lib.sh # Used by more than 1 bin
|   |-- civibuild.lib.sh
|   |-- cividist.lib.sh
|   `-- etc ...
`--- etc ...
```
Note that with this structure, some files would have more than 500 lines of code (I notice that already there are files with 700-800 lines). Is that alright ?

**Comment by ginkgomzd** [comment]
+1 for this effort.

What about also porting to php? In the past, I have had an easy time of porting bash scripts to php. I think this is bigger than any I have attempted.

Might it not help for the modularizing and unit testing?

**Comment by totten** [comment]
Agree it should be more modular. In particular, there are a bunch of functions inside `bin/civibuild` (e.g. `civibuild_run`, `civibuild_download`) which should be a library file.

Agree that it makes sense to put more function libraries under `src/*.lib.sh`.

FWIW, `absdirname` is a bit special. Think of it as boilerplate bootstrap logic. When `bin/civibuild` starts, it needs a way to determine PRJDIR so that it can load `src/civibuild.lib.sh` (or any other scripts or data in PRJDIR). The technique using `absdirname` is nice because it works regardless of `PWD` and regardless of how the command is addressed (e.g. `civibuild list` vs `./bin/civibuild list` vs `/srv/buildkit/bin/civibuild list`). 

There are probably a few functions where we could get high-impact from unit-testing (e.g. the new parameter-parsing function), but overall I think the bigger gap for `civibuild` is the e2e testing. Incidentally, having some e2e tests would also help with porting to another language (PHP).

**Comment by totten** [comment]
Just a note... about a month ago, there were several updates around this topic, specifically:

 * Breaking up `bin/civibuild` into some smaller files (`src/civibuild.parse.sh`, `src/civibuild.app.sh`, and `src/command/*.run.sh`). 
 * Adding some e2e tests in `tests/phpunit`

There are still some more things that could benefit from modularization (e.g. splitting `civibuild_app_usage()` into separate help files for each subcommand), and the test suite could use more coverage, but it's improved.
