### ISSUE TITLE
Deprecation of 'node' in favor of 'nodejs'.

### ISSUE THREAD

**Issue by saurabhbatra96** [civicrm/civicrm-buildkit#239]
The NodeJS interpreter name (node) has been changed to 'nodejs'. While installing, the following error occurs: 
```bash
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read /usr/share/doc/nodejs/README.Debian 
```
An easy fix that worked for me is installing the nodejs-legacy package. It might be nice to mention it in the documentation.

Further reading: [http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu](http://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu)

**Comment by mlutfy** [comment]
As far as I know, this is Debian/Ubuntu-specific, and NodeJS officially uses "node". Debian/Ubuntu should install the "nodejs-legacy" package. Is something missing in the dependancies/checks/documentation for that specific situation?

**Comment by saurabhbatra96** [comment]
I was testing something out with givi and had to re-install when I encountered this. I don't think it's there in the documentation anywhere. But, I must admit I did not check Civi's stackexchange page.

**Comment by totten** [comment]
Ditto mlutfy -- this is really a Debian-specific thing. All docs and tools outside debian.org use `node` instead of `nodejs`. Installing `nodejs-legacy` is the standard solution (which works with or without buildkit).

FWIW, at one point I got a bit short-tempered with recurring issues about this, so I put a work-around in [`bin/civi-download-tools`](https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L166 ) -- note how `nodejs_debian_workaround` which creates a symlink named `node`. This works even if you don't have `nodejs-legacy` installed. However, there are edge-cases where it could be broken. You might want to:
 * Check if buildkit has `bin/node` as a symlink to `/usr/bin/nodejs`. If not, update buildkit per README. If it still doesn't show up, then that's may be some kind of new bug/edge-case which would require you to dig into `civi-download-tools`.
 * Check if `PATH` includes buildkit's `bin` dir.

**Comment by totten** [comment]
Please feel free to update/reopen if you find issues (eg with the symlink for `bin/node` to `/usr/bin/nodejs`). However, as phrased originally, `node` won't be deprecated for `nodejs` (because that is Debian-specific).

**Comment by saurabhbatra96** [comment]
@totten Oh yes, I just wanted to point out that ``` node ``` had been deprecated in favor of ``` nodejs ``` by NPM on Ubuntu. Just thought it might be nice to include this somewhere in the documentation.
