### ISSUE TITLE
gencode requires MySQL connection

### ISSUE THREAD

**Issue by xurizaemon** [civicrm/civicrm-buildkit#283]
Well, TBH I just think it's gencode. I'm building CiviCRM tarballs for Fuzion, and without some MySQL configuration, gencode spits out a  lot of 

> Access denied for user ''@'localhost' (using password: NO)

when building the various DAO files, and the resulting tarballs contain invalid / missing SQL.

I looked for a config option to set a DSN, but failed to identify where it's set.

MySQL does not need a connection to any particular DB - it just wants a connection to pass to `mysql_real_escape_string()` I believe. So a workaround is,

    GRANT SELECT ON test.doesnotexist TO ''@localhost;

But I'd rather be able to configure the connection details than do this. How are others managing this in order to successfully build CiviCRM distribution tarballs?

**Comment by totten** [comment]
a) For sites created via `civibuild`, I generally don't call `xml/GenCode.php` directly -- instead, go through `bin/setup.sh -g`. The file `bin/setup.conf` should be pre-generated to provide suitable DB credentials.

b) If the issue is with `distmaker`... maybe `distmaker` should be using a similar setup?

c) PHP has INI options for `mysql.default_host`, `mysql.default_user`, and `mysql.default_password`. When you call GenCode directly, these are the values it should be reading. You can pass them via CLI (`php -d mysql.default_host=localhost ... xml/GenCode.php`) or store them in your `php.ini` file. This is what I've done in the past when put into a pinch.

d) It feels a bit silly that GenCode requires a SQL connection -- but that stems from a design issue in PHP's MySQL API's.

**Comment by totten** [comment]
It's not clear from the description, but I'm guessing this is an issue when you use `cividist` to run `distmaker.sh` which calls `${DM_PHP:-php} GenCode.php schema/Schema.xml $DM_VERSION $GENCODE_CMS`.

A couple ideas for fixing:
 * __Preflight check__: Update `cividist` or `GenCode` to include a pre-flight check that determines if a default SQL connection is working. If SQL doesn't work, display an error message encouraging the user to update `php.ini` (`mysql.default_host`, `mysql.default_user`, and `mysql.default_password`).
 * __Pass-through credentials__: In `app/config/dist/install.sh`, generate a file that provides access to DB settings. This might be `bin/setup.conf` or `distmaker/distmaker.conf`. Then, patch core's `distmaker.sh` to take advantage of the DB (like https://github.com/civicrm/civicrm-core/blob/4.7.12/bin/setup.sh#L184).
