### ISSUE TITLE
civilint skipping tools/extension directory

### ISSUE THREAD

**Issue by AkA84** [civicrm/civicrm-buildkit#387]
https://github.com/civicrm/civicrm-buildkit/blob/24e44e45c5eb6984625f90feb87282367fa22d53/bin/civilint#L54

I was implementing https://github.com/okonet/lint-staged in CiviHR
```json
{
  "scripts": {
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "*.php": "civilint"
  }
}
```
and noticed that civilint didn't seem to work at all (files with style issues would be committed straightaway instead of the linter giving an error report)

After some investigation I found out that lint-staged passes the full path to civilint
```
/Users/alessandro/GitHub/buildkit/build/hr17/sites/all/modules/civicrm/tools/extensions/civihr/hrjobcontract/CRM/Contact/Form/Inline/CustomData.php
```
instead of the path from the folder where the commit is being created
```
hrjobcontract/CRM/Contact/Form/Inline/CustomData.php
```

This turns out to be a problem for us, because in CiviHR we have our extensions in the `tools/extensions/` folder, and civilint skips the files in the `tools/` folder (see above)

Why is that though? As far as we know `tools/extensions` is an acceptable place to put the extensions, and it's even where the default extensions are placed in civicrm-core (see [here](https://github.com/civicrm/civicrm-core/tree/master/tools/extensions))

Would it be possible to remove `tools/` from the regex? Or at least whitelist `tools/extensions` ?

**Comment by totten** [comment]
Good question. There is no strong reason for "why" - mostly artifacts of history/capacity/priority. Excluding it means that no one has to clean it up.

There are several ways you might address this issue:

* Cleanup the content in `tools/` to pass the standards. (e.g. `eval $(find tools/ -name '*.php' | xargs echo phpcs-civi -a )` will walk through them). This is the most logically consistent, but it can feel uncomfortable to cleanup a file you don't know.
* Have CiviHR put its source code under `sites/all/modules/civicrm/ext` instead of `sites/all/modules/civicrm/tools/extensions`. (`civicrm-core` doesn't really care you call the subdir. I've taken to `ext` because it's a lot shorter.)
* Don't call `civilint` ; instead, call `phpcs-civi`.

**Comment by AkA84** [comment]
I wasn't really aware of `phpcs-civi`, i tried it and it works like a charm, thanks!
