### ISSUE TITLE
.dev sites on google chrome, etc.

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-buildkit#394]
Originally from https://github.com/civicrm/civicrm-buildkit-vagrant/issues/32

> 
> This is a minor quality of life issue.
> 
> Since version 66 (Dec 2017) Chrome now force redirects all sites ending in the .dev domain to https even on the localhost. see this write up on the issue.
> 
> This causes a server response error when trying to view the pre-generated sites on chrome (Other browsers work fine).
> 
> We can manually add/modify existing host setting but it if it is not too large a job it may be worth modifying the .dev to something else like .devel or .localhost in the default settings.
> 
> Again thank you so much for all the work on this project!
> 
>

**Comment by totten** [comment]
@michaelmcandrew @gobnat, I agree -- ideally, we should change the default. Chrome is a sort'a popular browser... 

For some history, `civibuild` was originally agnostic to the domain (or, rather, *as agnostic as underlying apps allowed*). It required the user to explicitly pass `--url htp://foo.bar` for every build. But it got a bit tiresome typing that regularly, so we added the `URL_TEMPLATE` option and set a default which matched the most commonly-observed usage (i.e `http://foo.dev`). You can trivially change the `URL_TEMPLATE` in `civibuild.conf` (which I typically do); then all your new builds will follow it.

But the point of this issue seems to be that *the **default** doesn't work with a web browser that is popular for web-dev*. So the game here is to *change a default*. And inevitably, somewhere downstream (like some system using a VM/vagrant/docker-based virtual-network), there's going to be an ill-effect because somebody relied on that default (e.g. they configured `dnsmasq` or some other tool to match the default `*.dev`).

My preference would be to keep the default on existing deployments, change the default on new deployments, and send a general communication of the key points:

1. Google is fucking shit up (breaking a common convention among web-devs).
2. For new installs, the default has changed.
3. For existing installs, you can opt-in to the change. If you do so, please throw away your existing builds and update any virtual-networking.

However, I can't think of a *simple* way to implement those changes. Making that kind of change will require something A Little Sketchy(tm).

On the other hand, maybe I'm overthinking it -- evidently, Google thinks it's OK to give a middle-finger to all the webdevs using `*.dev`, so maybe we should follow suit -- do the smallest possible change, send a PSA to `civicrm-dev@`, and say "Not my problem" to the rest?

**Comment by michaelmcandrew** [comment]
> somewhere downstream (like some system using a VM/vagrant/docker-based virtual-network), there's going to be an ill-effect

Only for new build - old ones will continue to work.

> On the other hand, maybe I'm overthinking it -- evidently, Google thinks it's OK to give a middle-finger to all the webdevs using *.dev, so maybe we should follow suit -- do the smallest possible change, send a PSA to civicrm-dev@, and say "Not my problem" to the rest?

I think it is OK for a breaking change like this to exist on a system that is primarily aimed and marketed towards creating development environments (as opposed to production ones): *"Buildkit is a collection of ~20 tools for developing and testing CiviCRM."*

Also, anyone that is using it in production will (you would assume) have changed the `URL_TEMPLATE` variable.

**Comment by chrisfromredfin** [comment]
I don't know how buildkit is *already* being used in the wild, as I'm generally new to this. However, from my newcomer's perspective I was trying to build a new custom entity type for CiviCRM using the instructions for civix entity:generate or whatever (the one that's still very Work-In-Progress), which then required the development build of CiviCRM, which led me to buildkit, which led me to the Vagrant VM (already using a Vagrant box for development), so I spun it all up according to default instructions and it didn't work out of the box.

I ultimately went over to @michaelmcandrew 's Docker build, but had separate issues over there, so I finally came back here and after wading through this issue and others tried manually to re-create the build command from inside the half-provisioned VM and was able to make it work by re-running the build passing a --url manually, and updating my hosts file manually.

So, from my perspective I vote for "don't do something A Little Sketchy(tm) and instead just give the middle finger, as Google did anyway." In short, .dev is broken in a LOT of places all over with this HSTS change, and it would be broken *I think* for any existing install anyway who didn't get around it some sketchy way already (like disabling HSTS in Firefox or something). 

Like @michaelmcandrew I believe that this tool is used primarily for development, so as long as you have backed up your work, you should be able to just re-spin-up a working buildkit and put your stuff back.

**Comment by xurizaemon** [comment]
See also civicrm/civicrm-buildkit-vagrant#40

**Comment by totten** [comment]
> ...RFC6761...

Sweet! `.test` sounds good to me.
